- name: Hello World Sample
  hosts: all
  tasks:
    - name: Hello Message
      debug:
        msg: "Hello World!"
      sleep: 30
    - name: Hello Message
      debug:
        msg: "Hello World!"
    - name: Hello Message
      debug:
        msg: "Hello World!"
    - name: Hello Message
      debug:
        msg: "Hello World!"
    - name: Hello Message
      debug:
        msg: "Hello World!"
    - name: Hello Message
      debug:
        msg: "Hello World!"
    - name: Hello Message
      debug:
        msg: "Hello World!"
    - name: Hello Message
      debug:
        msg: "Hello World!"
    - name: Hello Message
      debug:
        msg: "Hello World!"
    - name: Hello Message
      debug:
        msg: "Hello World!"
    - name: Hello Message
      debug:
        msg: "Hello World!"
    - name: Hello Message
      debug:
        msg: "Hello World!"
    - name: Hello Message
      debug:
        msg: "Hello World!"
    - name: Hello Message
      debug:
        msg: "Hello World!"
    - name: Hello Message
      debug:
        msg: "Hello World!"
    - name: Hello Message
      debug:
        msg: "Hello World!"
